services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"  # Bind host port 80 to container port 80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Mount Nginx config
  
  humidity:
    build: ./humidity
    expose:
      - "5005" 
  temp:
    build: ./temp
    expose:
      - "5005"
 
  wind:
    build: ./wind
    expose:
      - "5005"

  weatherman:
    build: ./weatherman
    expose:
      - "5005"
